{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Reading",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    { "expr": "sum(irate(read_success[1m]))", "legendFormat": "success" },
    {
     "expr": "sum by (type) ( irate(read_error[1m]))",
     "legendFormat": "errors.{{type}}"
    }
   ]
  },
  {
   "title": "Read Device",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rate(read_devices_latency_ms_sum[1m]) / rate(read_devices_latency_ms_count[1m]))"
    }
   ]
  },
  {
   "title": "Read Credentials",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rate(read_credentials_latency_ms_sum[1m]) / rate(read_credentials_latency_ms_count[1m]))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 } },
  {
   "title": "Parameters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(read_device_range)", "legendFormat": "range.selected" },
    { "expr": "avg(read_device_totals)", "legendFormat": "range.total" },
    {
     "expr": "sum(up{job_name=\"http-inserter\"})",
     "legendFormat": "inserters"
    }
   ]
  },
  {
   "title": "# reader",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job_name=\"http-reader\"})"
    }
   ]
  },
  {
   "title": "# inserter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job_name=\"http-inserter\"})"
    }
   ]
  },
  {
   "title": "# entries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "sum(write_success)", "legendFormat": "devices" }
   ]
  },
  {
   "title": "Writing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    { "expr": "sum(irate(write_success[1m]))", "legendFormat": "success" },
    {
     "expr": "sum by (type) ( irate(write_error[1m]))",
     "legendFormat": "errors.{{type}}"
    },
    {
     "expr": "sum(irate(write_success[1m])) / sum(up{job_name=\"http-inserter\"})",
     "legendFormat": "per-pod"
    }
   ]
  },
  {
   "title": "Register Device",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rate(write_devices_latency_ms_sum[1m]) / rate(write_devices_latency_ms_count[1m]))"
    }
   ]
  },
  {
   "title": "Set Credentials",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rate(write_credentials_latency_ms_sum[1m]) / rate(write_credentials_latency_ms_count[1m]))"
    }
   ]
  }
 ]
}